// Re-export everything from the DuckDB client
export {
  searchContributions,
  searchFilers,
  searchExpenditures,
  getFilerById,
  getTopDonors,
  getContributionsForFiler,
  formatCurrency,
  formatDate,
  formatDateInt,
  isDuckDBReady,
  waitForInit,
  query,
  type SearchFilters,
  type PaginationParams,
  type SearchResult,
  type Contribution,
  type Expenditure,
  type Filer,
  type Report,
} from './duckdb';
