// Re-export everything from the DuckDB client
export {
  searchContributions,
  searchFilers,
  searchExpenditures,
  getFilerById,
  getLatestReport,
  getTopDonors,
  getTopDonorsFiltered,
  getContributionsForFiler,
  getTimelineData,
  getReportTimeline,
  getFilerStatsFiltered,
  formatCurrency,
  formatDate,
  formatDateInt,
  isDuckDBReady,
  waitForInit,
  query,
  clearCache,
  getCacheInfo,
  onInitProgressChange,
  type SearchFilters,
  type PaginationParams,
  type SearchResult,
  type Contribution,
  type Expenditure,
  type Filer,
  type Report,
  type InitProgress,
  type InitStatus,
  type TimelineDataPoint,
  type LatestReport,
  type ReportTimelinePoint,
} from './duckdb';
